# -*- coding: utf-8 -*-
"""iris veriseti ile lojistik regrasyon

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RLawnyZOQ1VZ12I4ovjzDiSRPKUd75Yz
"""

from google.colab import files
files.upload()

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!pip install kaggle

import os
os.environ['KAGGLE_CONFIG_DIR'] = "/content"

!kaggle datasets download -d uciml/iris

import zipfile
with zipfile.ZipFile("iris.zip","r") as zip_ref:
    zip_ref.extractall("iris_data")

import pandas as pd

df = pd.read_csv("iris_data/Iris.csv")
print(df.head())

df.describe()  # Sayısal sütunların istatistikleri
df['Species'].value_counts()  # Her türden kaç tane var

import seaborn as sns
import matplotlib.pyplot as plt

sns.pairplot(df, hue='Species')
plt.show()

# 1️⃣ Gerekli kütüphaneler
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# 2️⃣ Veriyi oku
df = pd.read_csv("iris_data/Iris.csv")

# 3️⃣ Özellikler ve hedefi ayır
X = df.drop(['Id', 'Species'], axis=1)  # Özellikler
y = df['Species']                        # Hedef

# 4️⃣ Eğitim ve test verisi olarak ayır (80% eğitim, 20% test)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# 5️⃣ KNN modeli oluştur ve eğit (k=3)
model = KNeighborsClassifier(n_neighbors=3)
model.fit(X_train, y_train)

# 6️⃣ Test verisi ile tahmin yap
y_pred = model.predict(X_test)

# 7️⃣ Sonuçları göster
print("Doğruluk: ", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

# Özellikleri seç: PetalLengthCm ve PetalWidthCm
X_plot = X[['PetalLengthCm', 'PetalWidthCm']].values
y_plot = y.values

# Eğitim ve test setlerini ayır
X_train_plot, X_test_plot, y_train_plot, y_test_plot = train_test_split(
    X_plot, y_plot, test_size=0.2, random_state=42
)

# Modeli oluştur ve eğit
model_plot = KNeighborsClassifier(n_neighbors=3)
model_plot.fit(X_train_plot, y_train_plot)

# Test seti tahminleri
y_pred_plot = model_plot.predict(X_test_plot)

# Plot için renkler
colors = {'Iris-setosa':'red', 'Iris-versicolor':'green', 'Iris-virginica':'blue'}

# Test verisini ve tahminleri göster
plt.figure(figsize=(8,6))

# Gerçek türler (dairesel işaret)
for species in np.unique(y_test_plot):
    idx = np.where(y_test_plot == species)
    plt.scatter(X_test_plot[idx, 0], X_test_plot[idx, 1],
                c=colors[species], label=f"{species} (gerçek)",
                marker='o', edgecolor='k', s=80)

# Tahminler (çarpı işaret)
for species in np.unique(y_pred_plot):
    idx = np.where(y_pred_plot == species)
    plt.scatter(X_test_plot[idx, 0], X_test_plot[idx, 1],
                c=colors[species], label=f"{species} (tahmin)",
                marker='x', s=100)

plt.xlabel('PetalLengthCm')
plt.ylabel('PetalWidthCm')
plt.title('KNN Tahminleri - Iris Veri Seti')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(8,6))
sns.scatterplot(data=df, x='SepalLengthCm', y='SepalWidthCm', hue='Species', style='Species', s=100, palette="bright")
plt.title("Sepal Uzunluğu vs Sepal Genişliği")
plt.show()

plt.figure(figsize=(10,6))
sns.boxplot(x='Species', y='PetalLengthCm', data=df, palette="pastel")
plt.title("Türlere Göre Petal Length Dağılımı")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

# Sayısal sütunları seç
numeric_df = df.drop(['Id'], axis=1).select_dtypes(include='number')

plt.figure(figsize=(8,6))
sns.heatmap(numeric_df.corr(), annot=True, cmap='coolwarm')
plt.title("Özellikler Arası Korelasyon")
plt.show()

from sklearn.preprocessing import LabelEncoder

# LabelEncoder oluştur
le = LabelEncoder()

# Species sütununu sayısala çevir ve yeni sütun oluştur
df['Species_num'] = le.fit_transform(df['Species'])

# Kontrol
print(df.head())

from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

# PCA ile 2 boyuta indir
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X)

# 2D Scatter Plot
plt.figure(figsize=(8,6))
for species, color in zip(df['Species'].unique(), ['red', 'green', 'blue']):
    idx = df['Species'] == species
    plt.scatter(X_pca[idx, 0], X_pca[idx, 1], c=color, label=species, s=100, edgecolor='k')

plt.xlabel("PCA 1")
plt.ylabel("PCA 2")
plt.title("Görsel 6: PCA ile 2D Boyuta İndirgenmiş Iris Verisi")
plt.legend()
plt.show()

import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical

X_nn = df.drop(['Id','Species','Species_num'], axis=1).values
y_nn = to_categorical(df['Species_num'].values)

X_train_nn, X_test_nn, y_train_nn, y_test_nn = train_test_split(
    X_nn, y_nn, test_size=0.2, random_state=42
)

model_nn = Sequential([
    Dense(16, activation='relu', input_shape=(4,)),
    Dense(8, activation='relu'),
    Dense(3, activation='softmax')
])

model_nn.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

history = model_nn.fit(
    X_train_nn, y_train_nn,
    epochs=50,
    batch_size=16,
    validation_split=0.1
)

loss, acc = model_nn.evaluate(X_test_nn, y_test_nn)
print(f"Neural Network Test Doğruluk: {acc*100:.2f}%")

plt.figure(figsize=(8,5))
plt.plot(history.history['accuracy'], label='Eğitim Doğruluk')
plt.plot(history.history['val_accuracy'], label='Doğrulama Doğruluk')
plt.legend()
plt.show()

plt.figure(figsize=(8,5))
plt.plot(history.history['loss'], label='Eğitim Loss')
plt.plot(history.history['val_loss'], label='Doğrulama Loss')
plt.legend()
plt.show()

y_pred_nn = model_nn.predict(X_test_nn)
y_pred_classes = np.argmax(y_pred_nn, axis=1)
y_true_classes = np.argmax(y_test_nn, axis=1)

cm_nn = confusion_matrix(y_true_classes, y_pred_classes)

plt.figure(figsize=(7,6))
sns.heatmap(cm_nn, annot=True, fmt='d', cmap='Blues',
            xticklabels=le.classes_,
            yticklabels=le.classes_)
plt.show()